# -*- coding: utf-8 -*-
"""FeretDataAnalysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e2EAy4KhlVxjpMYmTPhqf30DZbcAfJhI

Below code tells about how we can retreive data from feret data set format.We will extract data from .bz2 and read .ppm file to convert it in jpg for further image processing.
"""

!pip install bz2file

import bz2
import matplotlib.pyplot as plt
import numpy as np
from PIL import Image
import os
import io
import cv2
from google.colab.patches import cv2_imshow

path = "/content/data"
for(dirpath,dirnames,files)in os.walk(path):
  for file in files:
    print(file)
    filepath = os.path.join(dirpath,file)
    uncompressedData = bz2.BZ2File(filepath).read()
    image=Image.open(io.BytesIO(uncompressedData))
    savepath=path+"/"+file+".jpg"
    image.save(savepath)
    img = cv2.imread(savepath)
    print(cv2_imshow(img) )

cv2.waitKey(0)   
cv2.destroyAllWindows()

